name: randomdom_flutter
description: RandomDom cross-platform app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  open_filex: ^4.7.0
  android_intent_plus: ^5.3.1
  path_provider: ^2.1.5
  device_apps_plus: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  windows:
    generate: true
    image_path: icon.png
    icon_size: 48
  image_path: icon.png
